name: First Workflow
run-name: ${{ github.actor }}
on: workflow_dispatch
jobs:
  first-job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello first time"
          echo "Hello second time"
      - name: Print Good bye
        run: |
          echo "Job Done"
          echo "Bye!"
